apiVersion: v1
kind: Service
metadata:
  name: automation-gateway
  namespace: apps
  labels:
    app: automation-gateway
spec:
  type: ClusterIP
  selector:
    app: automation-gateway
  ports:
  - name: http
    port: 8000
    targetPort: 8000
