apiVersion: v2
name: prometheus
description: Prometheus deployment for monitoring lab
type: application
version: 1.0.0

dependencies:
  - name: prometheus
    version: "28.5.2"
    repository: "https://prometheus-community.github.io/helm-charts"
